
import { Inter, Besley, Space_Grotesk, Playfair_Display, Satisfy, Teko, Phudu, Poppins, Onest } from "next/font/google";
import GlobalVideoModal from "@/components/Popup/GlobalVideoModal";
import { VideoProvider } from "@/provider/VideoProvider";
import AppProvider from "@/provider/AppProvider";
import Wrapper from "@/layouts/wrapper";
import type { Metadata } from "next";
import "swiper/css/bundle";
import "./globals.scss";

// Inter font – Supports weights from 100 to 900, including italic styles
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

// Besley font – Supports weights from 400 to 900, including italic styles
const besley = Besley({
  subsets: ["latin"],
  variable: "--font-besley",
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

// Space Grotesk font – Supports weights from 300 to 700
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

// Playfair Display font – Supports weights from 400 to 900, including italic styles
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

// Satisfy font – Only available in regular weight (400)
const satisfy = Satisfy({
  subsets: ["latin"],
  variable: "--font-satisfy",
  weight: "400",
  display: "swap",
});

// Teko font – Supports weights from 300 to 700
const teko = Teko({
  subsets: ["latin"],
  variable: "--font-teko",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

// Phudu font – Supports weights from 300 to 900
const phudu = Phudu({
  subsets: ["latin"],
  variable: "--font-phudu",
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

// Poppins font – Supports weights from 100 to 900, including italic styles
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

// Onest font – Supports weights from 100 to 900
const onest = Onest({
  subsets: ["latin"],
  variable: "--font-onest",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Agntix - Digital Agency & Creative Portfolio NextJs Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="no-js agntix-light" suppressHydrationWarning={true}>
      <body  suppressHydrationWarning={true} className={`tp-magic-cursor ${inter.variable}
     ${besley.variable} ${spaceGrotesk.variable} ${playfairDisplay.variable}
      ${satisfy.variable} ${teko.variable} ${phudu.variable} ${poppins.variable}
       ${onest.variable}`}>
        <AppProvider>
          <Wrapper>
            <VideoProvider>
                {children}
            </VideoProvider>
            <GlobalVideoModal />
          </Wrapper>
        </AppProvider>
      </body>
    </html>
  );
}